---
deployment:
    tasks:
        - export DEPLOYPATH=/home/zaribfnz/public_html/
        -  /bin/cp -R -f build/css $DEPLOYPATH
        -  /bin/cp -R -f build/images $DEPLOYPATH
        -  /bin/cp -R -f build/js $DEPLOYPATH
        -  /bin/cp -R -f build/static $DEPLOYPATH
        -  /bin/cp -f build/asset-manifest.json $DEPLOYPATH
        -  /bin/cp -f build/favicon.ico $DEPLOYPATH
        -  /bin/cp -f build/index.html $DEPLOYPATH
        -  /bin/cp -f build/manifest.json $DEPLOYPATH
        -  /bin/cp -f build/resumeData.json $DEPLOYPATH
        -  /bin/cp -f build/service-worker.js $DEPLOYPATH
    