---
deployment:
    tasks:
        - export DEPLOYPATH=/home/zaribfnz/public_html/
        - yes | /bin/cp -R -f css $DEPLOYPATH
        - yes | /bin/cp -R -f images $DEPLOYPATH
        - yes | /bin/cp -R -f js $DEPLOYPATH
        - yes | /bin/cp -R -f static $DEPLOYPATH
        - yes | /bin/cp -f asset-manifest.json $DEPLOYPATH
        - yes | /bin/cp -f favicon.ico $DEPLOYPATH
        - yes | /bin/cp -f index.html $DEPLOYPATH
        - yes | /bin/cp -f manifest.json $DEPLOYPATH
        - yes | /bin/cp -f resumeData.json $DEPLOYPATH
        - yes | /bin/cp -f service-worker.js $DEPLOYPATH
    